const SET_URL = 'SET_URL';
const SET_HAS_PLAY = 'SET_HAS_PLAY';
const SET_IS_STOP = 'SET_IS_STOP';
const HAS_DONE = 'HAS_DONE';
const TOAST_STATE = 'TOAST_STATE';
const IS_PC = 'IS_PC';
const HAS_PROGRAMINFO_DONE = 'HAS_PROGRAMINFO_DONE';
const HAS_PROGRAMLIST_DONE = 'HAS_PROGRAMLIST_DONE';
const PLAYCONTENT_PIC = 'PLAYCONTENT_PIC';
const PLAYAREASHOW = 'PLAYAREASHOW';
const PLAYID = 'PLAYID';
const NAVTITLE = 'NAVTITLE';
const CATEGORIESDATA = 'CATEGORIESDATA';



export {
    SET_URL,
    SET_HAS_PLAY,
    SET_IS_STOP,
    HAS_DONE,
    TOAST_STATE,
    IS_PC,
    HAS_PROGRAMINFO_DONE,
    HAS_PROGRAMLIST_DONE,
    PLAYCONTENT_PIC,
    PLAYAREASHOW,
    PLAYID,
    NAVTITLE,
    CATEGORIESDATA
};